#!/usr/bin/env bash

# Setup GOPATH
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=/usr/local/go/bin:$PATH

/usr/local/go/bin/go env -w GO111MODULE=on
/usr/local/go/bin/go env -w GOPROXY=https://goproxy.io,direct